# Configure.
language: python
python: 3.4
sudo: false

# Run.
install: pip install -r docs/requirements.txt docker-compose
script:
  - docker-compose config
  - sphinx-build -W docs docs/_build/html
after_success:
  - eval "$(ssh-agent -s)"; touch docs/key; chmod 0600 docs/key
  - openssl aes-256-cbc -d -K "$encrypted_d82f5b0a4dc8_key" -iv "$encrypted_d82f5b0a4dc8_iv"
    < docs/key.enc > docs/key && ssh-add docs/key
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git remote set-url --push origin "git@github.com:$TRAVIS_REPO_SLUG"
  - export ${!TRAVIS*}
  - sphinx-versioning push docs gh-pages .
