version: '3'

services:
  nginx:
    image: nginx
    ports: ['3000:3000', '8086:8086']
    restart: always
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/filesrv.rob86.net.cert.pem:/etc/ssl/cert.pem:ro
      - /etc/filesrv.rob86.net.key.pem:/etc/ssl/key.pem:ro

  influxdb:
    container_name: influxdb
    environment: [INFLUXDB_HTTP_AUTH_ENABLED=true]
    image: influxdb
    restart: always
    volumes: ['/storage/Local/influxdb:/var/lib/influxdb']

  grafana:
    container_name: grafana
    environment: [GF_SECURITY_DISABLE_GRAVATAR=true, GF_USERS_ALLOW_SIGN_UP=false]
    image: grafana/grafana
    restart: always
    volumes: ['/storage/Local/grafana:/var/lib/grafana']
