version: '3.1'

services:
  nginx:
    image: nginx
    ports: ['3000:3000', '8086:8086']
    restart: always
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/filesrv.rob86.net.cert.pem:/etc/ssl/cert.pem:ro
      - /etc/filesrv.rob86.net.key.pem:/etc/ssl/key.pem:ro

  influxdb:
    container_name: influxdb
    env_file:
     - ./influxdb.env
    environment:
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_HTTP_LOG_ENABLED=false
    image: influxdb
    restart: always
    volumes: ['./influxdb/data:/var/lib/influxdb']

  grafana:
    container_name: grafana
    #entrypoint: 'bash -c "cp /run/secrets/grafana /etc/grafana/grafana.ini && . run.sh"'  # TODO: Use secrets uid/mode
    
    image: grafana/grafana
    restart: always
    volumes: ['./grafana/data:/var/lib/grafana']


  
