version: '3'

networks:
  backend: {}

services:
  influxdb:
    container_name: influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_HTTP_HTTPS_ENABLED=true
    image: influxdb
    networks: [backend]
    ports: ['8086:8086']
    restart: always
    volumes:
      - /etc/filesrv.rob86.net.pem:/etc/ssl/influxdb.pem
      - /storage/Local/influxdb:/var/lib/influxdb
