version: '3.1'

services:
  nginx:
    image: nginx
    ports: ['3000:3000', '8086:8086']
    restart: always
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/filesrv.rob86.net.cert.pem:/etc/ssl/cert.pem:ro
      - /etc/filesrv.rob86.net.key.pem:/etc/ssl/key.pem:ro

  influxdb:
    container_name: influxdb
    environment: [INFLUXDB_HTTP_AUTH_ENABLED=true]
    image: influxdb
    restart: always
    volumes: ['/storage/Local/influxdb:/var/lib/influxdb']

  grafana:
    container_name: grafana
    entrypoint: 'bash -c "cp /var/run/secrets/grafana /etc/grafana/grafana.ini && ./run.sh"'  # TODO: Use secrets: -mode
    environment:
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_SMTP_ENABLED=true
      - GF_SMTP_FROM_ADDRESS=grafana@robpol86.com
      - GF_SMTP_HOST=smtp.sparkpostmail.com:587
      - GF_SMTP_USER=SMTP_Injection
      - GF_USERS_ALLOW_SIGN_UP=false
    image: grafana/grafana
    restart: always
    secrets: [grafana]
    volumes: ['/storage/Local/grafana:/var/lib/grafana']

  pimon:
    build: ./pimon
    container_name: pimon
    restart: always
    volumes: ['/storage/Local/raspberrypi:/root/copy:ro']

secrets:
  grafana:
    file: .secrets/grafana.ini
